# Taken almost verbatim from the original, except it didn't package this correctly so it wasn't distributed at all

import typing
import pathlib

class Hash:
    @staticmethod
    def from_rgb_pixels(
        width: int, height: int, pixels: list[tuple[int, int, int]]
    ) -> Hash: ...
    @staticmethod
    def from_image_path(path: str | pathlib.Path) -> Hash: ...
    @staticmethod
    def from_hex_str(hex_string: str) -> Hash: ...
    @staticmethod
    def from_bytes(byte_data: bytes) -> Hash: ...
    def as_bytes(self) -> bytes: ...
    def to_hex_str(self) -> str: ...
    def distance_euclidian(self, other: Hash) -> float: ...
    def similarity_euclidian(self, other: Hash) -> float: ...
    def distance_log2p(self, other: Hash) -> float: ...
    def similarity_log2p(self, other: Hash) -> float: ...

__all__ = [
    "Hash",
]
