[build-system]
requires = ["hatchling", "hatch-build-scripts"]
build-backend = "hatchling.build"

[project]
name = "sd-toolkit"
dynamic = ["version"]
description = "A suite of tools to assist in dataset preparation, LoRA training and LoRA management. Made for personal use."
readme = "README.md"
requires-python = ">=3.14"
authors = [
  { name = "abel1502" },
]
dependencies = [
    "anyquests>=1.0.1",
    "anywidget>=0.11.0",
    "attrs>=26.1.0",
    "cattrs[cbor2,orjson]>=26.1.0",
    "frozendict>=2.4.7",
    "loguru>=0.7.3",
    "nanotable[sorted]>=0.1.1",
    "pyarrow>=24.0.0",
    "pydantic>=2.13.4",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "sortedcontainers>=2.4.0",
    "sqlitedict>=2.1.0",
    "tqdm>=4.67.3",
    "types-frozendict>=2.0.9",
    "typing-extensions>=4.15.0",
]
classifiers = [
  "Private :: Do Not Upload",
]

[dependency-groups]
dev = [
    "anywidget[dev]>=0.11.0",
    "pytest>=9.1.0",
    "pytest-cov>=7.1.0",
]

[project.urls]
Documentation = "https://github.com/abel1502/sd-toolkit#readme"
Issues = "https://github.com/abel1502/sd-toolkit/issues"
Source = "https://github.com/abel1502/sd-toolkit"

[tool.hatch.version]
path = "src/sd_toolkit/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/sd_toolkit"]
artifacts = ["src/sd_toolkit/static"]

[[tool.hatch.build.hooks.build-scripts.scripts]]
work_dir = "widget_svelte"
commands = ["pnpm run build"]


[tool.coverage.run]
source_pkgs = ["sd_toolkit", "tests"]
branch = true
parallel = true
omit = [
  "src/sd_toolkit/__about__.py",
]

[tool.coverage.paths]
sd_toolkit = ["src/sd_toolkit", "*/sd-toolkit/src/sd_toolkit"]
tests = ["tests", "*/sd-toolkit/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cover",
  "if __name__ == .__main__.:",
  "if (typing\\.)?TYPE_CHECKING:",
  "^\\s*\\.\\.\\.\\s*($|#)",
]
